### ISSUE TITLE
Regarding the question mark notation

### ISSUE THREAD

**Issue by pgrosu** [common-workflow-language/cwljava#20]
@mr-c Can you help me please with pointing me to some documentation, where the question is described and how to interpret it?  For example, in [metaschema.yml on lines 170-171](https://github.com/common-workflow-language/common-workflow-language/blob/25784a9682b76df40dd3dcd529de8890043596b9/v1.0/salad/schema_salad/metaschema/metaschema.yml#L170-L171) I see the following:

```

- name: DocType
  type: record
  abstract: true
  fields:
    - name: doc
      type:
        - string?
        - string[]?
```

Thanks,
Paul
