### ISSUE TITLE
Fails to parse requirements correctly

### ISSUE THREAD

**Issue by jdidion** [common-workflow-language/cwljava#31]
When I parse this workflow, the resulting `CommandLineToolImpl` contains two copies of the `InlineJavascriptRequirement`.

```yaml
cwlVersion: v1.2

class: CommandLineTool

requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entryname: emptyWritableDir
        entry: "$({class: 'Directory', listing: []})"
        writable: true

hints:
  - class: DockerRequirement
    dockerPull: alpine

inputs: []
outputs:
  out:
    type: Directory
    outputBinding:
      glob: emptyWritableDir
arguments: [touch, emptyWritableDir/blurg]
```
